export const instruments = [
  {
      id: 1,
      name: "Fender Guitar",
      price: 300,
      image_url: "https://th.yamaha.com/en/files/fgx5_gloss_9c8be17d4682da0a25ad85d884c83cb1.jpg?impolicy=resize&imwid=396&imhei=396",
      like: 20,
      is_new: true,
  },
  {
      id: 2,
      name: "Yamaha Piano",
      price: 700,
      image_url: "https://guitarhunter.dk/wp-content/uploads/2024/09/img_0707-500x500.jpg.webp",
      like: 15,
      is_new: false,
  },
  {
      id: 3,
      name: "Gibson Acoustic Guitar",
      price: 450,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq5AIMQmt4VnS0xns2vyrExeeniNYyQmiDsA&s",
      like: 30,
      is_new: true,
  },
  {
      id: 4,
      name: "Drum Set",
      price: 500,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnbXXpHz-hSLmLMKQnzipFrZKWCL1BLfNa1A&s",
      like: 25,
      is_new: false,
  },
  {
      id: 5,
      name: "Fender Guitar",
      price: 300,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBt2iw-VPmIJsPB-6xNRZyPFPmhEvQDJFFLQ&s",
      like: 20,
      is_new: true,
  },
  {
      id: 6,
      name: "Yamaha Piano",
      price: 1200,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6NKTiDSfYzIv0ctKhAkR1jznvXq9-hVAChg&s",
      like: 35,
      is_new: false,
  },
  {
      id: 7,
      name: "Yamaha Piano",
      price: 700,
      image_url: "https://guitarhunter.dk/wp-content/uploads/2024/09/img_0707-500x500.jpg.webp",
      like: 15,
      is_new: false,
  },
  {
      id: 8,
      name: "Ibanez Bass Guitar",
      price: 450,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT358nzkNRbbrkBi8_tBYJdHe5arWNljI5Qmg&s",
      like: 15,
      is_new: true,
  },
  {
      id: 9,
      name: "Roland Drum Set",
      price: 700,
      image_url: "https://m.media-amazon.com/images/I/71z7svZWSFL.jpg",
      like: 25,
      is_new: false,
  },
  {
      id: 10,
      name: "Selmer Saxophone",
      price: 800,
      image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvklE0hQCdjk9OgDquL4jdq0NLe-pXOOcPAQ&s",
      like: 40,
      is_new: true,
  },
];
