import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "../component/head"
import Foot from "../component/foot";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Head />
        <main>
          {children}
        </main>
        <Foot />
        </body>
    </html>
  );
}
